## 5.7 保存/読み込み

In [1]:
import numpy as np

large_x = np.random.randint(0,10, size=1_000_000).reshape(1000,1000)
large_x.shape

(1000, 1000)

In [2]:
large_x[-2:]

array([[9, 3, 1, ..., 6, 4, 7],
       [4, 6, 1, ..., 2, 4, 5]])

In [3]:
# テキストファイルとして保存、区切り文字 ','
np.savetxt('large_x.csv', large_x, delimiter=',')

In [4]:
# テキストファイルの読み込み、区切り文字 ','
x2=np.loadtxt('large_x.csv', delimiter=',')
x2.shape


(1000, 1000)

In [5]:
x2[-2:]

array([[9., 3., 1., ..., 6., 4., 7.],
       [4., 6., 1., ..., 2., 4., 5.]])

In [6]:
# バイナリファイルとして保存
np.save('large_x', large_x)
x3 = np.load('large_x.npy')
x3.shape

(1000, 1000)

In [7]:
x3[-2:]

array([[9, 3, 1, ..., 6, 4, 7],
       [4, 6, 1, ..., 2, 4, 5]])

In [8]:
# 圧縮バイナリファイルとして保存
np.savez_compressed('large_x2', a=large_x)
loaded = np.load('large_x2.npz')
print(loaded["a"])

[[7 8 6 ... 5 2 4]
 [7 9 5 ... 4 8 6]
 [0 2 7 ... 2 9 4]
 ...
 [9 6 1 ... 5 6 2]
 [9 3 1 ... 6 4 7]
 [4 6 1 ... 2 4 5]]


## 5.8 一次元配列に変換する

In [9]:
large_x

array([[7, 8, 6, ..., 5, 2, 4],
       [7, 9, 5, ..., 4, 8, 6],
       [0, 2, 7, ..., 2, 9, 4],
       ...,
       [9, 6, 1, ..., 5, 6, 2],
       [9, 3, 1, ..., 6, 4, 7],
       [4, 6, 1, ..., 2, 4, 5]])

In [10]:
x2 = large_x.ravel()
x2

array([7, 8, 6, ..., 2, 4, 5])

In [11]:
x2.shape

(1000000,)

In [12]:
x3 = large_x.flatten() 
x3.shape


(1000000,)

In [13]:
x4 = large_x.reshape(-1) # -1を与えると、１次元配列になる
x4.shape

(1000000,)