## 5.3. ndarrayの操作

### 5.3.1 生成

In [1]:
import numpy as np

# numpy 基礎
a = np.array([0,1,2,3,4,5]) # 1次元配列
b = np.array([(0,1,2), (3,4,5)]) # 2次元配列
c = np.array([[[0,1,2],
               [3,4,5]],
             [[6,7,8],
               [9,10,11]]]) # 3次元配列 2x2x3

print("a: ", a)
print("type(a): ", type(a))
print("b: ", b)
print("c: ", c)

print(len(c)) # 3次元配列の長さ
print(len(c[0])) # 3次元配列の行
print(len(c[0][0])) # 3次元配列の列


a:  [0 1 2 3 4 5]
type(a):  <class 'numpy.ndarray'>
b:  [[0 1 2]
 [3 4 5]]
c:  [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
2
2
3


In [34]:
# 配列生成関数を使用し、配列の作成
z1 = np.zeros(3) # '0' 3個要素の１次元配列
z2 = np.zeros((3,3)) # '0' 3x3個要素の２次元配列
one1 = np.ones(3)  # '1' 3個要素の１次元配列
one2 = np.ones((3,3)) # '1' 3x3個要素の２次元配列

print("zero1: ", z1)
print("zero2: ", z2)
print("one1: ", one1)
print("one2: ", one2)

# '0'から '6'未満まで '1'ずつ増加する１次元数列
#　(組み込み関数rangeと類似)
ar1 = np.arange(0, 6, 1, dtype=np.int8)
print("arange " , ar1)

lin1 = np.linspace(1, 2, 3)

# 初期化されていない値で配列を作成
print("empty(5): ", np.empty(5))
e1 = np.empty((2,3))

# 4x4単位行列の作成
e2 = np.eye(4)

# 2x3行列を作って, 値20で全て埋める
f1 = np.full((2,3),20)

# 標準正規分布乱数
ran1 = np.random.rand(2,3)
# ガウス分布の‘標準正規分布’の乱数
ran2 = np.random.randn(2,3)


print("linspace: " , lin1)
print("empty: " , e1)
print("eye: " , e2)
print("full: ", f1)
print("random1: ", ran1)
print("random2: ", ran2)

zero1:  [0. 0. 0.]
zero2:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
one1:  [1. 1. 1.]
one2:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arange  [0 1 2 3 4 5]
empty(5):  [0.00000000e+000 9.09679207e-312 9.09679206e-312 9.09679207e-312
 0.00000000e+000]
linspace:  [1.  1.5 2. ]
empty:  [[0.17459407 3.27734066 0.00472778]
 [0.41431432 0.17808271 0.41498564]]
eye:  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
full:  [[20 20 20]
 [20 20 20]]
random1:  [[0.93339554 0.43199321 0.04248375]
 [0.61767437 0.46804253 0.35681243]]
random2:  [[-0.58238341  1.44436514 -0.17519613]
 [ 0.58740781  1.83465303  0.72616649]]


In [35]:
np.dtype('i4')

dtype('int32')

In [36]:
np.dtype('?')

dtype('bool')

### 5.3.3 属性：次元数と形状、データ型

In [37]:
# 配列の形状
print(a.ndim) # 配列の次元数または軸数
print(a.shape) # 配列の各次元のサイズを表現
print(a.dtype) # 配列の要素のデータ型

print(b.ndim)
print(b.shape)

print(c.ndim)
print(c.shape)

1
(6,)
int32
2
(2, 3)
3
(2, 2, 3)


In [38]:
# 配列全体要素数
print(a.size)
print(b.size)
print(c.size)

6
6
12


### 5.3.4 転置

In [66]:
# 配列の転置（行と列を反転）
print(a)
print(a.T) # 転置、同じ結果
print(b.T) # 転置、行と列が反転します

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]


In [67]:
c.transpose(0,2,1) # 最初の次元をそのままにし、2番目と3番目の軸を変更

array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])

In [41]:
c.swapaxes(0,1) # 3番目の次元をそのままにし、1番目と2番目の軸を変更

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])

### 5.3.5 インデキシングとスライシング

In [42]:
# 配列インデキシング
print(b[0, 1]) # bの2次元配列の最初の行の2番目の列
print(b[1, 2]) # bの2次元配列の2番目の行の3番目の列
print(c[0,1,1]) # cの3次元配列の最初の次元の2番目の行、2番目の列

1
5
4


In [43]:
# 配列スライシング
print(c[0, :2, :2]) # cの3次元配列の最初の次元から2番目の行まで、2番目の列まで

[[0 1]
 [3 4]]


### 5.3.6 配列の形状を変更する

In [44]:
b = np.array([(0,1,2), (3,4,5)], dtype="uint8") # 2次元配列
print(b)

[[0 1 2]
 [3 4 5]]


In [45]:
# 配列の形状を変更する
b.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]], dtype=uint8)

### 5.3.7 fancy indexing(ファンシ ー インデキシング)

In [46]:
import numpy as np

fancy_arr = np.arange(3*3*2, dtype="uint8")
fancy_arr = fancy_arr.reshape(3,2,3)
fancy_arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]], dtype=uint8)

In [47]:
# fancy indexing
# 1次元目の最初の要素から2番目の配列
fancy_arr[[0],[1]]

array([[3, 4, 5]], dtype=uint8)

In [48]:
fancy_arr[[0],[1],[2,1,0]]

array([5, 4, 3], dtype=uint8)

In [49]:
fancy_arr[[-1],[0],[2,1,0]]

array([14, 13, 12], dtype=uint8)

### 5.3.8 配列の算術演算

In [50]:
# 配列の算術
arr1 = np.random.rand(2,3)
arr1

array([[0.45637349, 0.78044259, 0.17314826],
       [0.65807256, 0.38453913, 0.36835133]])

In [51]:
arr2 = np.random.randn(2,3)
arr2

array([[-1.56396201,  0.50636468, -1.26811836],
       [-2.17016288, -0.26192206, -0.23538259]])

In [52]:
arr3 = arr1 * arr2
arr3


array([[-0.71375081,  0.39518857, -0.21957249],
       [-1.42812463, -0.10071928, -0.08670349]])

In [53]:
arr4 = np.ones((2,3)) * 2 # 全ての要素を２倍する
arr4


array([[2., 2., 2.],
       [2., 2., 2.]])

In [54]:
arr2 ** 2 # 全ての要素を２乗する

array([[2.44597717, 0.25640519, 1.60812416],
       [4.70960692, 0.06860316, 0.05540496]])

### 5.3.9  配列の結合と分割

In [55]:
# 配列の結合
np.concatenate([b,b])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]], dtype=uint8)

In [56]:
# 列基準の配列結合
np.concatenate([b,b], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]], dtype=uint8)

In [57]:
a1 = np.array([(0,1,2,3), (4,5,6,7)] , dtype="uint8") # 2次元配列
b1 = np.array([(10,11,12,13), (14,15,16,17)] , dtype="uint8") # 2次元配列

# 行基準で結合
np.vstack((a1,b1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [10, 11, 12, 13],
       [14, 15, 16, 17]], dtype=uint8)

In [58]:
# 列基準で結合
np.hstack((a1,b1))

array([[ 0,  1,  2,  3, 10, 11, 12, 13],
       [ 4,  5,  6,  7, 14, 15, 16, 17]], dtype=uint8)

In [59]:
b2 = np.array([(0,1,2,3), (4,5,6,7)] , dtype="uint8") # 2次元配列

# 行基準で2部分に分割
np.split(b2,2)

[array([[0, 1, 2, 3]], dtype=uint8), array([[4, 5, 6, 7]], dtype=uint8)]

In [60]:
# 行基準で2部分に分割
np.vsplit(b2,2)

[array([[0, 1, 2, 3]], dtype=uint8), array([[4, 5, 6, 7]], dtype=uint8)]

In [61]:
# 列基準で2部分に分割
np.hsplit(b2,2)

[array([[0, 1],
        [4, 5]], dtype=uint8),
 array([[2, 3],
        [6, 7]], dtype=uint8)]

### 5.3.10 条件文による配列の抽出

In [62]:
arr1 = np.random.rand(2,3)
arr2 = np.random.randn(2,3)
arr2 = arr2 ** 2

arr2

array([[0.84449122, 0.45176813, 0.33361295],
       [0.10220427, 0.6477398 , 0.67518911]])

In [63]:
# 条件、arr2 配列要素の中で、１より大きい数のみ抽出
arr2[ arr2 > 1]

array([], dtype=float64)

In [64]:
# 条件に合致するインデックスを出力
np.where( arr2 > 1)

(array([], dtype=int64), array([], dtype=int64))

In [65]:
# 条件に合致する場合には「Yes」と出力
np.where( arr2 > 1, 'Yes', arr1)

array([['0.33411969707582023', '0.06606890004699895',
        '0.5259292959307359'],
       ['0.2507424139894304', '0.26620559746011396',
        '0.044029892867933684']], dtype='<U32')