### 5.4.3 合計、平均、標準偏差、分散、累積値の計算

In [1]:
import numpy as np
x = np.arange(1,7).reshape((2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
# 配列要素の合計を計算する
np.sum(x) # = x.sum()

21

In [3]:
# 配列要素の平均を計算する
np.mean(x) # = x.mean()

3.5

In [4]:
# 配列要素の標準偏差を計算する
np.std(x)

1.707825127659933

In [5]:
# 配列要素の分散を計算する
np.var(x)


2.9166666666666665

In [6]:
# 指定された軸に沿って配列要素の累積和を計算する
np.cumsum(x) # = x.comsum()


array([ 1,  3,  6, 10, 15, 21])

In [7]:
# 指定された軸に沿って配列要素の累積積を計算する
np.cumprod(x)

array([  1,   2,   6,  24, 120, 720])

### 5.4.4 乱数の生成

In [8]:
import numpy as np

np.random.rand(3,4)

array([[0.83960794, 0.47024329, 0.2844517 , 0.25398158],
       [0.61418091, 0.45363166, 0.19454765, 0.54728142],
       [0.31283623, 0.36369834, 0.09710925, 0.79378215]])

In [9]:
np.random.randint(4) # [0,4) 範囲乱数

1

In [10]:
np.random.randint(1,4) # [1,4) 範囲乱数

3

In [11]:
np.random.randint(1,4, size=10) # [0,4) 範囲１０個乱数

array([3, 2, 2, 1, 1, 1, 1, 2, 3, 2])

In [12]:
np.random.randn(2,3)

array([[-2.21807065,  0.34260139, -0.50467019],
       [-1.12486876,  1.07755937, -0.84733045]])

In [13]:
np.random.standard_normal((2,3))

array([[ 0.10288134,  0.34849574, -0.41742992],
       [ 0.96958089,  2.02255172,  0.4459961 ]])

In [14]:
np.random.normal(1,1,size=(3,3))

array([[ 1.35760411,  0.3258781 ,  2.08662496],
       [-0.88482516, -1.10482041,  3.51026817],
       [ 1.03637471,  1.56238646,  0.09969951]])