### 5.4.1 代表的な単項ユニバーサル関数

In [1]:
import numpy as np

# 四捨五入
np.around([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -2.,  2., -3.,  2., -2.])

In [2]:
# 切り上げ: 同じ整数または最も近い大きい整数を返す
np.ceil([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 2., -1.,  2., -2.,  3., -2.])

In [3]:
# 切り捨て: 同じ整数または最も近い小さい整数を返す
np.floor([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -2.,  2., -3.,  2., -3.])

In [4]:
# 端数切り捨て
np.trunc([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -1.,  2., -2.,  2., -2.])

In [5]:
# 最も近い整数に四捨五入
np.rint([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -2.,  2., -3.,  2., -2.])

In [6]:
# 0に最も近い整数に丸める
np.fix([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1., -1.,  2., -2.,  2., -2.])

In [7]:
# 絶対値の計算: 整数、浮動小数点数、複素数
np.abs([1.1, -1.6, 2, -2.7, 2.01, -2.01, 1+2j])

array([1.1       , 1.6       , 2.        , 2.7       , 2.01      ,
       2.01      , 2.23606798])

In [8]:
np.absolute([1.1, -1.6, 2, -2.7, 2.01, -2.01, 1+2j])

array([1.1       , 1.6       , 2.        , 2.7       , 2.01      ,
       2.01      , 2.23606798])

In [9]:
# 絶対値の計算: 整数、浮動小数点数 (absより速い)
np.fabs([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([1.1 , 1.6 , 2.  , 2.7 , 2.01, 2.01])

In [10]:
# 平方根を計算する
np.sqrt([1,4,9,21])

array([1.        , 2.        , 3.        , 4.58257569])

In [11]:
# 立方根を計算する
np.cbrt([1,8,27])

array([1., 2., 3.])

In [12]:
# 二乗を計算する
np.square([1,4,9,21])

array([  1,  16,  81, 441])

In [13]:
# 小数部と整数部に分ける
np.modf([1.1, -1.6, 2, -2.7, 2.01, -2.01, 0])

(array([ 0.1 , -0.6 ,  0.  , -0.7 ,  0.01, -0.01,  0.  ]),
 array([ 1., -1.,  2., -2.,  2., -2.,  0.]))

In [14]:
# 符号判定: 1(正数)、0(ゼロ)、-1(負数)
np.sign([1.1, -1.6, 2, -2.7, 2.01, -2.01, 0])

array([ 1., -1.,  1., -1.,  1., -1.,  0.])

In [15]:
# 複素数の虚部の符号を反転
np.conj([1+2j, 1-3j, 2-6j])

array([1.-2.j, 1.+3.j, 2.+6.j])

In [16]:
np.conjugate([1+2j, 1-3j, 2-6j])

array([1.-2.j, 1.+3.j, 2.+6.j])

In [17]:
# 1を乗算
np.positive([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([ 1.1 , -1.6 ,  2.  , -2.7 ,  2.01, -2.01])

In [18]:
# 符号反転: -1を乗算
np.negative([1.1, -1.6, 2, -2.7, 2.01, -2.01])

array([-1.1 ,  1.6 , -2.  ,  2.7 , -2.01,  2.01])

In [19]:
# 配列の最大値を計算する
np.max([1.1, -1.6, 2, -2.7, 2.01, -2.01])

2.01

In [20]:
# 配列の最小値を計算する
np.min([1.1, -1.6, 2, -2.7, 2.01, -2.01])

-2.7

In [21]:
# 配列の最大値のインデックスを返す
np.argmax([1.1, -1.6, 2, -2.7, 2.01, -2.01])

4

In [22]:
# 配列の最小値のインデックスを返す
np.argmin([1.1, -1.6, 2, -2.7, 2.01, -2.01])

3

In [23]:
# 25%のパーセンタイルを計算する
np.percentile([1.1, -1.6, 2, -2.7, 2.01, -2.01], 25)

-1.9074999999999998

In [24]:
# 50%のパーセンタイルを計算する
np.percentile([1.1, -1.6, 2, -2.7, 2.01, -2.01], 50)

-0.25

In [25]:
# 配列要素の中央値（メジアン）を計算する
np.median([1.1, -1.6, 2, -2.7, 2.01, -2.01])

-0.25

In [26]:
# 配列要素の平均を計算する
np.mean([1.1, -1.6, 2, -2.7, 2.01, -2.01])

-0.20000000000000004

In [27]:
# 要素を[e^要素値]に計算する
np.exp([1,2,3,4,5])


array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [28]:
# 要素を[2^要素値]に計算する
np.exp2([1,2,3,4,5])

array([ 2.,  4.,  8., 16., 32.])

In [29]:
# 底がeの対数
np.log([0.0000000002, 2, 6])


array([-22.33270375,   0.69314718,   1.79175947])

In [30]:
# 底がeの対数。ただし、log(1+x)の形; logで値が0に近いと発散する問題を補完
np.log1p([0.0000000002, 2, 6])

array([2.00000000e-10, 1.09861229e+00, 1.94591015e+00])

In [31]:
# 底が2の対数
np.log2([0.0000000002, 2, 6])

array([-32.21928095,   1.        ,   2.5849625 ])

In [32]:
# 底が10の対数
np.log10([0.0000000002, 2, 6])

array([-9.69897   ,  0.30103   ,  0.77815125])

In [33]:
# NaNならTrue、その他はFalseを返す
np.isnan([np.nan, np.inf, np.log1p(2), 2.])

array([ True, False, False, False])

In [34]:
# 有限数ならTrue、その他はFalseを返す
np.isfinite([1.,2.,4.,5., np.nan, np.inf, np.NINF])

array([ True,  True,  True,  True, False, False, False])

In [35]:
# 無限大ならTrue、その他はFalseを返す
np.isinf([1.,2.,4.,5., np.nan, np.inf, np.NINF])

array([False, False, False, False, False,  True,  True])

In [36]:
# 逆数(1/要素値)を計算する
np.reciprocal([1.,2.,4.,5.])

array([1.  , 0.5 , 0.25, 0.2 ])

In [37]:
# 論理NOT演算を計算する
np.logical_not([True, True, True, False])

array([False, False, False,  True])