## 5.5 配列のソート

In [1]:
import numpy as np
x = np.random.normal(1,1,size=(3,3))
x

array([[ 1.2348282 ,  1.36141627,  2.11799226],
       [-0.55379911,  1.13430188, -0.62966429],
       [-0.12696405,  2.51252839, -0.44915345]])

In [2]:
# 各行の要素をソート
np.sort(x)

array([[ 1.2348282 ,  1.36141627,  2.11799226],
       [-0.62966429, -0.55379911,  1.13430188],
       [-0.44915345, -0.12696405,  2.51252839]])

In [3]:
# 各列の要素をソート
np.sort(x, axis=0)

array([[-0.55379911,  1.13430188, -0.62966429],
       [-0.12696405,  1.36141627, -0.44915345],
       [ 1.2348282 ,  2.51252839,  2.11799226]])

In [4]:
# 逆順にソート
np.sort(x, axis=1)[::-1]

array([[-0.44915345, -0.12696405,  2.51252839],
       [-0.62966429, -0.55379911,  1.13430188],
       [ 1.2348282 ,  1.36141627,  2.11799226]])

In [5]:
# 昇順にソートした時のインデックス
np.argsort(x)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 0, 1]], dtype=int64)

In [6]:
import numpy as np
x1 = np.array([10, 20, 30, 10, 10])
y1 = np.array([40, 10, 10, 20, 30])
idx = np.lexsort((y1, x1))
idx

array([3, 4, 0, 1, 2], dtype=int64)

In [7]:
# ソート の 結果 を 出力
for i in idx:
  print(x1[i], y1[i])

10 20
10 30
10 40
20 10
30 10


### 5.6 集合メソッド

In [8]:
import numpy as np

x = [1,2,2,2,3,3,4,4,5,5,5,6]
y = [1,1,1,2,3,4,4,4,5,6,6,7,7]
np.unique(x)

array([1, 2, 3, 4, 5, 6])

In [9]:
np.union1d(x,y) # x, y 和集合を計算し、その一意の値を返す

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
np.intersect1d(x,y) # x, y 積集合を計算し、その一意の値を返す

array([1, 2, 3, 4, 5, 6])

In [11]:
np.setdiff1d(y, x) # xのy差集合を計算し、その一意の値を返す

array([7])

In [12]:
np.in1d(y,x) # x要素がyに含まれているかブーリアン値を返す

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False])