### 5.4.2 二項ユニバーサル関数

In [1]:
import numpy as np
x = np.arange(1,7).reshape((2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
y = np.arange(1,4)
y

array([1, 2, 3])

In [3]:
# add
x+y

array([[2, 4, 6],
       [5, 7, 9]])

In [4]:
# subtract
np.subtract(x,y)

array([[0, 0, 0],
       [3, 3, 3]])

In [ ]:
# 符号反転
x + np.negative(y)

array([[0, 0, 0],
       [3, 3, 3]])

In [6]:
# 乗算
np.multiply(x,y)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [7]:
# 除算
np.divide(x, y)

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [8]:
# x要素をy要素で除した商から最大の整数
np.floor_divide(x,y)

array([[1, 1, 1],
       [4, 2, 2]])

In [9]:
# x要素をy要素で累乗
np.power(x,y)

array([[  1,   4,  27],
       [  4,  25, 216]])

In [10]:
# x要素をy要素で除した余り
np.mod(x,y)

array([[0, 0, 0],
       [0, 1, 0]])

In [11]:
# x要素とy要素の最大公約数
np.gcd(x, y)

array([[1, 2, 3],
       [1, 1, 3]])

In [12]:
# x要素とy要素の最大値。fmaxはNaNを無視
np.maximum([[1,2,3],[4,5,np.nan]], y)

array([[ 1.,  2.,  3.],
       [ 4.,  5., nan]])

In [13]:
np.fmax([[1,2,3],[4,5,np.nan]], y)

array([[1., 2., 3.],
       [4., 5., 3.]])

In [14]:
# x要素とy要素の最小値。fminはNaNを無視
np.minimum([[1,2,3],[4,5,np.nan]], y)

array([[ 1.,  2.,  3.],
       [ 1.,  2., nan]])

In [15]:
np.fmin([[1,2,3],[4,5,np.nan]],y)

array([[1., 2., 3.],
       [1., 2., 3.]])

In [16]:
# x要素がy要素より大きいかブーリアン値で返す
np.greater(x,y)

array([[False, False, False],
       [ True,  True,  True]])

In [17]:
# x要素がy要素より大きいか等しいかブーリアン値で返す
np.greater_equal(x,y)

array([[ True,  True,  True],
       [ True,  True,  True]])

In [18]:
x >= y

array([[ True,  True,  True],
       [ True,  True,  True]])

In [19]:
# x要素がy要素より小さいかブーリアン値で返す
np.less(x,y)

array([[False, False, False],
       [False, False, False]])

In [20]:
x < y

array([[False, False, False],
       [False, False, False]])

In [21]:
# x要素がy要素より小さいか等しいかブーリアン値で返す
np.less_equal(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [22]:
# x要素がy要素と等しいかブーリアン値で返す
np.equal(x,y)

array([[ True,  True,  True],
       [False, False, False]])

In [23]:
# x要素がy要素と等しくないかブーリアン値で返す
np.not_equal(x,y)

array([[False, False, False],
       [ True,  True,  True]])

In [24]:
# x要素とy要素の論理AND演算
np.logical_and([True, True, True, False],[False, False, False, False])

array([False, False, False, False])

In [25]:
# x要素とy要素の論理OR演算
np.logical_or([True, True, True, False],[False, False, False, False])

array([ True,  True,  True, False])

In [26]:
# x要素とy要素の論理XOR演算
np.logical_xor([True, True, True, False],[False, False, False, False])


array([ True,  True,  True, False])